on:
  push:
    branches-ignore: main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run test
      - run: bun run check
      - run: bun run build
      - run: bun run build:e2e
      - run: git diff --exit-code "src/$routes.d.ts"
