name: Test

on:
  push:
    branches-ignore: main
    paths:
      - src/**
      - test/**
      - '*.json'
      - '*.js'
      - '*.ts'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run test
      - run: bun run check
      - run: bun run build
      - run: bun run build:e2e
      - run: git diff --exit-code 'src/$routes.d.ts'
